name: feature_flags_demo_1 tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        deno-version: [1.21.0]

    steps:
      - name: Git Checkout feature_flags_demo_1
        uses: actions/checkout@v2
      - name: Use Deno Version ${{ matrix.deno-version }}
        uses: denolib/setup-deno@v2
        with:
          deno-version: ${{ matrix.deno-version }}
      - name: feature_flags_demo_1 tests
        run: deno test --allow-read --allow-net